

version: "2"

services:
  nodeosd:
    container_name: nodeosd
	image: eosio/eos:latest
	command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
	hostname: nodeosd
	ports:
	  - 8888:8888
	  - 9876:9876
	expose:
	  - "8888"
	volumes:
	  - /opt/eosio/data:/opt/eosio/bin/data-dir

  keosd:
    container_name: keosd
	image: eosio/eos:latest
	command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
	hostname: keosd
	links:
	  - nodeosd
	volumes:
	  - /opt/eosio/data:/opt/eosio/bin/data-dir


